version: '3'

services:
  bet.aspnetcore.webapi:
    image: ${DOCKER_REGISTRY-}betaspnetcorewebapi
    build:
      context: .
      dockerfile: src/Bet.ML.WebApi.Sample/Dockerfile
      args:
        RUNTESTS: "false"
        VERBOSE: "false"
        #NUGET_RESTORE: "-f" #overides the --disable-parallel
        PROJECT_PATH: "/src/Bet.ML.WebApi.Sample/Bet.ML.WebApi.Sample.csproj"
        SOLUTION_BASE: "false"

  bet.hosting:
    image: ${DOCKER_REGISTRY-}bethosting
    build:
      context: .
      dockerfile: src/Bet.Hosting.Sample/Dockerfile
      args:
        RUNTESTS: "false"
        VERBOSE: "false"
        #NUGET_RESTORE: "-f" #overides the --disable-parallel
        PROJECT_PATH: "/src/Bet.Hosting.Sample/Bet.Hosting.Sample.csproj"
        SOLUTION_BASE: "false"

  bet.aspnetcore.web:
    image: ${DOCKER_REGISTRY-}betaspnetweb
    build:
      context: .
      dockerfile: src/Bet.AspNetCore.Sample/Dockerfile
      args:
        RUNTESTS: "false"
        VERBOSE: "false"
        #NUGET_RESTORE: "-f" #overides the --disable-parallel
        PROJECT_PATH: "/src/Bet.AspNetCore.Sample/Bet.AspNetCore.Sample.csproj"
        SOLUTION_BASE: "false"
