version: '3'

services:
  bet.aspnetcore.build:
    image: ${DOCKER_REGISTRY-}betaspnetcore
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "1.0.0-preview"

  bet.aspnetcore.tests:
    image: ${DOCKER_REGISTRY-}betaspnetcore
    entrypoint: dotnet test --logger trx --results-directory /var/temp
    depends_on:
      - bet.aspnetcore.build
    volumes:
      - ${SYSTEM_DEFAULTWORKINGDIRECTORY:-.}/TestResults/:/var/temp

  bet.aspnetcore.nuget:
    image: ${DOCKER_REGISTRY-}betaspnetcore
    entrypoint: cp -r /app/nugets /
    depends_on:
      - bet.aspnetcore.build
    volumes:
       - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./nugets/}:/nugets
