#------------------------------------------------------------------------------------------------------------------------
#
# docker-compose -f "docker-compose.yml" -f "docker-compose.override.yml" up -d --no-recreate bet.hosting
#
# docker-compose -f "docker-compose.yml"  up  -d --no-recreate bet.hosting
#------------------------------------------------------------------------------------------------------------------------

version: '3.4'

services:
   bet.hosting:
    image: ${DOCKER_REGISTRY-}/bet:hosting
    build:
      context: .
      dockerfile: src/Bet.Hosting.Sample/Dockerfile
      args:
        RUNTESTS: "false"
        VERBOSE: "false"
        NUGET_RESTORE: "-v=m" #overides the --disable-parallel
        PROJECT_PATH: "/src/Bet.Hosting.Sample/Bet.Hosting.Sample.csproj"
        SOLUTION_BASE: "false"
